### ISSUE TITLE
Mejorar el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-irenegf83#1]
Super buen trabajo @irenegf83 

Algunas pistas para mejorarlo:

- [x] Mueve el `li` fuera del componente 'Pokemon', de esta manera Pokemon es un componente con una tarjeta que podemos usar en diferentes sitios y no solo dentro de un `ul`
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Elimina el código comentado
- [x] Apaña estilos (un archivo sass o css por componente)
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar la tarjeta con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by irene-gomez** [comment]
Hi @nasivuela!
I think I've got it all.
I wait for your answer if I lack something.

**Comment by nasivuela** [comment]
Excelente!!

Cierro y te dejo intentando que guardes el estado de los favoritos en App ;)

Y por último, si te animas añade una página de detalle para cada pokemon y así practicamos el router.

![](https://media.giphy.com/media/ToMjGpnXBTw7vnokxhu/giphy.gif)
